name: Publish
env:
  VERSION: 1.0.0
  NODE_VERSION: '22.21.1'
  TZ: 'America/Chicago'

on:
  push:
    tags:
      - "*"
      - "!*beta*"

jobs:
  publish:
    name: Publish on npm.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Validate types
        run: yarn run validate-ts

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
